global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: AKIA5ECUYB6VZZDI4F7V
        secret_key: 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
        port: 9100
